"""silver_labels.py — Opus's silver-quality labels for the eval-set candidates.

PR2 Phase A. Each entry is keyed by the row INDEX of
`eval_set_candidates.jsonl` (the ordering of build_eval_set.py's output).
`label` is True iff the article is genuinely about `candidate_story`;
`conf` is high/medium/low; optional `note` records a one-line reason for
non-obvious calls.

These labels are SILVER, not GOLD: they reflect Opus's judgment after
reading title + first 500 chars of signal_text per row. They are
stronger than regex weak supervision because they account for
near-neighbor disambiguation and non-Latin-script content, but they are
not multi-annotator human gold. The benchmark in `benchmark_models.py`
treats this as the ground truth against which LaBSE / e5 / BGE-M3 are
scored.

Convention for `label`:
  True  = article IS about `candidate_story`
  False = article is NOT about `candidate_story` (even if a regex
          keyword matched, the central topic is different)

Convention for `conf`:
  high   = unambiguous; a careful reader would not disagree
  medium = topic overlap exists; reasonable readers might disagree
  low    = thin signal_text (e.g. title-only stub); call uncertain
"""
LABELS = {
    # hormuz_iran (000-028) ----------------------------------------
    0: {"label": True, "conf": "high"},
    1: {"label": True, "conf": "high"},
    2: {"label": True, "conf": "high"},
    3: {"label": True, "conf": "high"},
    4: {"label": True, "conf": "high", "note": "Iran-Israel war with Hormuz context"},
    5: {"label": True, "conf": "high", "note": "Pakistan LNG bet on Hormuz tensions"},
    6: {"label": True, "conf": "high", "note": "Project Freedom is the Hormuz framework"},
    7: {"label": True, "conf": "high"},
    8: {"label": True, "conf": "high"},
    9: {"label": False, "conf": "high", "note": "iran_nuclear (plutonium pathway), not Hormuz"},
    10: {"label": True, "conf": "medium", "note": "Epic Fury = Hormuz op, but topic is nuclear deterrence"},
    11: {"label": True, "conf": "medium", "note": "Ship off Qatar in Hormuz region"},
    12: {"label": True, "conf": "high", "note": "Maritime chokepoints, Hormuz centered"},
    13: {"label": True, "conf": "medium", "note": "US-Iran ship attacks in Strait"},
    14: {"label": False, "conf": "medium", "note": "Iran deal w/ enrichment/missile focus = iran_nuclear"},
    15: {"label": True, "conf": "high"},
    16: {"label": False, "conf": "medium", "note": "Pentagon munitions surge; only indirect Hormuz link"},
    17: {"label": False, "conf": "high", "note": "Japanese hantavirus cruise; hint match on イラン was spurious"},
    18: {"label": False, "conf": "high", "note": "Iran domestic water shortage"},
    19: {"label": False, "conf": "medium", "note": "Mojtaba Khamenei politics, not Hormuz"},
    20: {"label": True, "conf": "high"},
    21: {"label": True, "conf": "medium", "note": "Saudi Aramco energy shock from Iran war"},
    22: {"label": False, "conf": "low", "note": "Title-only stub on Iran ceasefire"},
    23: {"label": False, "conf": "low", "note": "Iran deal Trump pressure, not Hormuz-specific"},
    24: {"label": False, "conf": "medium", "note": "US economic pressure on Iran, not Hormuz"},
    25: {"label": False, "conf": "high"},
    26: {"label": False, "conf": "high"},
    27: {"label": False, "conf": "high"},
    28: {"label": False, "conf": "high"},

    # turner_cnn (029-039) -----------------------------------------
    29: {"label": True, "conf": "high"},
    30: {"label": True, "conf": "high"},
    31: {"label": True, "conf": "high"},
    32: {"label": True, "conf": "high"},
    33: {"label": False, "conf": "low", "note": "Signal is literally just 'turner' — too thin"},
    34: {"label": True, "conf": "medium", "note": "Atlantic obit; entrepreneur framing"},
    35: {"label": True, "conf": "high"},
    36: {"label": True, "conf": "high", "note": "Japanese: CNN founder Ted Turner died"},
    37: {"label": False, "conf": "high"},
    38: {"label": False, "conf": "high"},
    39: {"label": False, "conf": "high"},

    # lebanon_buffer (040-067) -------------------------------------
    40: {"label": True, "conf": "high"},
    41: {"label": True, "conf": "high"},
    42: {"label": True, "conf": "high"},
    43: {"label": True, "conf": "high"},
    44: {"label": True, "conf": "high"},
    45: {"label": True, "conf": "medium", "note": "IDF evacuation orders mentioned in headline list"},
    46: {"label": True, "conf": "high"},
    47: {"label": True, "conf": "high", "note": "Portuguese: Israeli army threatens Hezbollah south Lebanon"},
    48: {"label": True, "conf": "high"},
    49: {"label": False, "conf": "high", "note": "Ukraine Mariupol — spurious regex match"},
    50: {"label": True, "conf": "high"},
    51: {"label": False, "conf": "medium", "note": "Gaza flotilla; only brief Hezbollah mention"},
    52: {"label": False, "conf": "medium", "note": "Hormuz ship; only side-mention of Beirut"},
    53: {"label": True, "conf": "high"},
    54: {"label": True, "conf": "medium", "note": "Iron Dome incl. Hezbollah"},
    55: {"label": True, "conf": "high"},
    56: {"label": True, "conf": "high", "note": "Arabic: Lebanese-Israeli negotiations"},
    57: {"label": True, "conf": "high", "note": "Farsi: Netanyahu-Lebanese president meeting"},
    58: {"label": False, "conf": "medium", "note": "Farsi: UAE-Iran-Lebanon politics; Lebanon side-mentioned"},
    59: {"label": True, "conf": "high"},
    60: {"label": True, "conf": "high"},
    61: {"label": True, "conf": "high"},
    62: {"label": True, "conf": "high"},
    63: {"label": True, "conf": "high"},
    64: {"label": True, "conf": "high"},
    65: {"label": False, "conf": "high"},
    66: {"label": False, "conf": "high"},
    67: {"label": False, "conf": "high"},

    # hantavirus_cruise (068-089) ----------------------------------
    68: {"label": False, "conf": "medium", "note": "Mexican governor news; hantavirus not in signal_text"},
    69: {"label": True, "conf": "high"},
    70: {"label": True, "conf": "high"},
    71: {"label": True, "conf": "high"},
    72: {"label": True, "conf": "high"},
    73: {"label": True, "conf": "high"},
    74: {"label": True, "conf": "high"},
    75: {"label": True, "conf": "high"},
    76: {"label": True, "conf": "high"},
    77: {"label": False, "conf": "high", "note": "NPR headline bundle: actually about US-Iran ship attacks"},
    78: {"label": True, "conf": "high"},
    79: {"label": True, "conf": "high"},
    80: {"label": False, "conf": "high", "note": "Japanese bus accident; hantavirus only in sidebar"},
    81: {"label": True, "conf": "high"},
    82: {"label": True, "conf": "high"},
    83: {"label": True, "conf": "high"},
    84: {"label": True, "conf": "high"},
    85: {"label": False, "conf": "high", "note": "Japanese bus accident; hantavirus only in related-links"},
    86: {"label": True, "conf": "high"},
    87: {"label": False, "conf": "medium", "note": "Korean: Trump 'liberation project' (not hantavirus)"},
    88: {"label": False, "conf": "high"},
    89: {"label": False, "conf": "high"},

    # vietnam_china_visit (090-105) --------------------------------
    # Story is SPECIFICALLY To Lam's visit to BEIJING. Vietnam visits
    # elsewhere (Sri Lanka, India) don't match.
    90: {"label": False, "conf": "medium", "note": "To Lam to Sri Lanka, not Beijing"},
    91: {"label": True, "conf": "high"},
    92: {"label": False, "conf": "medium", "note": "Vietnam South China Sea land reclamation, not the visit"},
    93: {"label": False, "conf": "high", "note": "Vietnam ambassador to NK"},
    94: {"label": False, "conf": "high", "note": "To Lam to New Delhi, not Beijing"},
    95: {"label": False, "conf": "medium", "note": "Vietnam economic reforms generally"},
    96: {"label": False, "conf": "high", "note": "To Lam departs for India"},
    97: {"label": False, "conf": "medium", "note": "Vietnam-Sri Lanka partnership upgrade"},
    98: {"label": False, "conf": "high", "note": "Vietnam-India strategic partnership"},
    99: {"label": False, "conf": "high", "note": "Wistron Q1 earnings"},
    100: {"label": False, "conf": "medium", "note": "Vietnam housing market"},
    101: {"label": False, "conf": "medium", "note": "Japanese PM Takaichi visits Vietnam (different visit)"},
    102: {"label": False, "conf": "high"},
    103: {"label": False, "conf": "high"},
    104: {"label": False, "conf": "high"},
    105: {"label": False, "conf": "high"},

    # iran_nuclear (106-133) ---------------------------------------
    106: {"label": True, "conf": "high"},
    107: {"label": False, "conf": "medium", "note": "Rappler ASEAN photos; nuclear only stray match"},
    108: {"label": True, "conf": "high"},
    109: {"label": True, "conf": "high"},
    110: {"label": True, "conf": "high"},
    111: {"label": True, "conf": "high"},
    112: {"label": True, "conf": "high"},
    113: {"label": True, "conf": "medium", "note": "Trump asks workers re Iran nuclear weapon"},
    114: {"label": True, "conf": "high"},
    115: {"label": True, "conf": "high"},
    116: {"label": True, "conf": "high"},
    117: {"label": True, "conf": "high"},
    118: {"label": True, "conf": "high", "note": "Trump-Xi: Iran nuclear among topics"},
    119: {"label": True, "conf": "high"},
    120: {"label": True, "conf": "high"},
    121: {"label": True, "conf": "medium", "note": "Iran ceasefire ship Hormuz + roll back nuclear"},
    122: {"label": True, "conf": "medium", "note": "Farsi: Trump warning re non-nuclear deal"},
    123: {"label": False, "conf": "high", "note": "Russian: US uranium from Venezuela"},
    124: {"label": True, "conf": "high"},
    125: {"label": False, "conf": "high"},
    126: {"label": False, "conf": "high"},
    127: {"label": True, "conf": "high"},
    128: {"label": False, "conf": "medium", "note": "Farsi: US restricts SK on NK nuclear info"},
    129: {"label": True, "conf": "high"},
    130: {"label": False, "conf": "high"},
    131: {"label": False, "conf": "high"},
    132: {"label": False, "conf": "high"},
    133: {"label": False, "conf": "medium", "note": "Iran no role in UAE op; not nuclear"},

    # ukraine_war (134-163) ----------------------------------------
    134: {"label": True, "conf": "high"},
    135: {"label": True, "conf": "high"},
    136: {"label": True, "conf": "high"},
    137: {"label": True, "conf": "high"},
    138: {"label": True, "conf": "high"},
    139: {"label": True, "conf": "high"},
    140: {"label": True, "conf": "high"},
    141: {"label": False, "conf": "medium", "note": "Pedro Sanchez politics; only side mention of Ukraine"},
    142: {"label": True, "conf": "high"},
    143: {"label": False, "conf": "medium", "note": "EU Montenegro accession; Ukraine loan side-mention"},
    144: {"label": True, "conf": "high", "note": "Dup of 134"},
    145: {"label": True, "conf": "high"},
    146: {"label": False, "conf": "medium", "note": "South Asian military lessons from Ukraine — about I-P not Ukraine"},
    147: {"label": True, "conf": "high"},
    148: {"label": True, "conf": "high"},
    149: {"label": True, "conf": "high"},
    150: {"label": False, "conf": "medium", "note": "Pentagon munitions surge; Ukraine indirect"},
    151: {"label": False, "conf": "medium", "note": "Nuclear nonproliferation"},
    152: {"label": True, "conf": "high"},
    153: {"label": True, "conf": "medium", "note": "Putin paranoia article — about Russia / war regime"},
    154: {"label": True, "conf": "high"},
    155: {"label": True, "conf": "high"},
    156: {"label": True, "conf": "medium", "note": "Solovyov propaganda — about Russia's war-time image"},
    157: {"label": True, "conf": "high"},
    158: {"label": True, "conf": "high"},
    159: {"label": True, "conf": "high"},
    160: {"label": True, "conf": "high"},
    161: {"label": True, "conf": "medium", "note": "Albanian PM critique of EU Russia policy"},
    162: {"label": True, "conf": "high"},
    163: {"label": False, "conf": "high", "note": "Cloudflare label — unrelated"},

    # china_taiwan (164-186) ---------------------------------------
    164: {"label": True, "conf": "high"},
    165: {"label": True, "conf": "high"},
    166: {"label": True, "conf": "high"},
    167: {"label": True, "conf": "high"},
    168: {"label": True, "conf": "high"},
    169: {"label": True, "conf": "high"},
    170: {"label": True, "conf": "high", "note": "China pressure campaign on Zambia conference"},
    171: {"label": True, "conf": "high"},
    172: {"label": True, "conf": "high"},
    173: {"label": True, "conf": "high"},
    174: {"label": True, "conf": "medium", "note": "Taiwan Strait among chokepoints"},
    175: {"label": False, "conf": "high"},
    176: {"label": True, "conf": "high", "note": "PLA assessment of Taiwan defense"},
    177: {"label": False, "conf": "high"},
    178: {"label": False, "conf": "high"},
    179: {"label": True, "conf": "high"},
    180: {"label": False, "conf": "high"},
    181: {"label": True, "conf": "high"},
    182: {"label": True, "conf": "high"},
    183: {"label": False, "conf": "medium", "note": "NHK US-Iran Hormuz; Taiwan only in sidebar"},
    184: {"label": False, "conf": "high"},
    185: {"label": False, "conf": "high"},
    186: {"label": False, "conf": "high"},

    # climate_policy (187-202) -------------------------------------
    187: {"label": True, "conf": "high"},
    188: {"label": True, "conf": "high"},
    189: {"label": False, "conf": "medium", "note": "Farage UK politics; net-zero side mention"},
    190: {"label": True, "conf": "high"},
    191: {"label": True, "conf": "high"},
    192: {"label": False, "conf": "medium", "note": "Australian budget; climate side mention"},
    193: {"label": True, "conf": "medium", "note": "Heathrow net-zero / biomass"},
    194: {"label": True, "conf": "high"},
    195: {"label": True, "conf": "high"},
    196: {"label": False, "conf": "medium", "note": "AI mosquito surveillance; climate adaptation indirect"},
    197: {"label": False, "conf": "high"},
    198: {"label": False, "conf": "high"},
    199: {"label": False, "conf": "high"},
    200: {"label": False, "conf": "high"},
    201: {"label": False, "conf": "high"},
    202: {"label": False, "conf": "medium", "note": "Gas tax suspension — climate-adjacent but not policy story"},

    # ai_regulation (203-223) --------------------------------------
    203: {"label": False, "conf": "medium", "note": "Burgum AI Teddy — tangential"},
    204: {"label": True, "conf": "high"},
    205: {"label": True, "conf": "high"},
    206: {"label": True, "conf": "high"},
    207: {"label": True, "conf": "high"},
    208: {"label": True, "conf": "high"},
    209: {"label": True, "conf": "high"},
    210: {"label": True, "conf": "high"},
    211: {"label": True, "conf": "high"},
    212: {"label": False, "conf": "medium", "note": "AI applied to mosquito surveillance, not AI regulation"},
    213: {"label": True, "conf": "medium", "note": "Meta + AI Islamophobia content moderation"},
    214: {"label": False, "conf": "medium", "note": "Iran's AI investments, not regulation"},
    215: {"label": False, "conf": "high"},
    216: {"label": False, "conf": "high"},
    217: {"label": False, "conf": "high"},
    218: {"label": False, "conf": "high"},
    219: {"label": False, "conf": "medium", "note": "AI generation as side detail"},
    220: {"label": False, "conf": "high"},
    221: {"label": False, "conf": "high"},
    222: {"label": False, "conf": "high"},
    223: {"label": False, "conf": "high"},

    # israel_palestine (224-251) -----------------------------------
    224: {"label": True, "conf": "high"},
    225: {"label": False, "conf": "high", "note": "Russia-Ukraine ceasefire"},
    226: {"label": True, "conf": "high"},
    227: {"label": True, "conf": "high"},
    228: {"label": True, "conf": "high"},
    229: {"label": True, "conf": "high"},
    230: {"label": True, "conf": "high"},
    231: {"label": True, "conf": "high"},
    232: {"label": True, "conf": "high"},
    233: {"label": False, "conf": "high", "note": "Russia-Ukraine ceasefire"},
    234: {"label": False, "conf": "medium", "note": "IDF Hezbollah W Galilee = lebanon_buffer"},
    235: {"label": False, "conf": "medium", "note": "Israel/Iran deal terms = iran_nuclear"},
    236: {"label": True, "conf": "medium", "note": "Iron Dome incl. Hamas missiles"},
    237: {"label": False, "conf": "medium", "note": "Israel strikes Beirut = lebanon_buffer"},
    238: {"label": True, "conf": "high"},
    239: {"label": False, "conf": "medium", "note": "Israel-Hezbollah ceasefire = lebanon_buffer"},
    240: {"label": True, "conf": "high"},
    241: {"label": False, "conf": "medium", "note": "Naim Qassem Hezbollah Galilee = lebanon_buffer"},
    242: {"label": True, "conf": "high"},
    243: {"label": False, "conf": "medium", "note": "Tehran response Hormuz = hormuz_iran"},
    244: {"label": True, "conf": "medium", "note": "Israel-Argentina air route"},
    245: {"label": True, "conf": "high"},
    246: {"label": True, "conf": "high"},
    247: {"label": True, "conf": "medium", "note": "Amnesty regional ceasefire incl. Gaza"},
    248: {"label": True, "conf": "high"},
    249: {"label": False, "conf": "high"},
    250: {"label": False, "conf": "high"},
    251: {"label": False, "conf": "high"},

    # india_pakistan (252-273) -------------------------------------
    252: {"label": False, "conf": "medium", "note": "Heatwave South Asia; not bilateral"},
    253: {"label": True, "conf": "high"},
    254: {"label": False, "conf": "high", "note": "J&K domestic drug crackdown"},
    255: {"label": True, "conf": "high"},
    256: {"label": True, "conf": "high"},
    257: {"label": True, "conf": "high"},
    258: {"label": True, "conf": "high"},
    259: {"label": True, "conf": "high"},
    260: {"label": False, "conf": "medium", "note": "J-K CM Omar Delhi meeting (domestic)"},
    261: {"label": True, "conf": "high"},
    262: {"label": False, "conf": "medium", "note": "Pakistan mediator Iran-US, not I-P"},
    263: {"label": False, "conf": "high"},
    264: {"label": False, "conf": "high"},
    265: {"label": False, "conf": "medium", "note": "SC bail Bangladeshi cross-border (India-Bangladesh)"},
    266: {"label": False, "conf": "high"},
    267: {"label": False, "conf": "high"},
    268: {"label": False, "conf": "medium", "note": "BSF Bangladesh border fencing"},
    269: {"label": False, "conf": "high"},
    270: {"label": False, "conf": "high"},
    271: {"label": False, "conf": "medium", "note": "Hebrew: ships stuck in Hormuz war"},
    272: {"label": False, "conf": "high"},
    273: {"label": False, "conf": "high"},

    # us_election_cycle (274-294) ----------------------------------
    274: {"label": True, "conf": "high"},
    275: {"label": True, "conf": "high"},
    276: {"label": True, "conf": "medium", "note": "Philippine VP impeach explicitly framed at 2028 bid"},
    277: {"label": True, "conf": "high"},
    278: {"label": True, "conf": "high"},
    279: {"label": True, "conf": "high"},
    280: {"label": True, "conf": "high"},
    281: {"label": True, "conf": "high", "note": "Philippine VP impeach 2028"},
    282: {"label": True, "conf": "high"},
    283: {"label": False, "conf": "medium", "note": "Telangana state 2028 (not US)"},
    284: {"label": False, "conf": "high", "note": "Trump-Iran nuclear (not US elections)"},
    285: {"label": False, "conf": "medium", "note": "UK local election (not US)"},
    286: {"label": False, "conf": "high"},
    287: {"label": False, "conf": "high"},
    288: {"label": False, "conf": "high"},
    289: {"label": False, "conf": "high"},
    290: {"label": False, "conf": "high"},
    291: {"label": False, "conf": "high"},
    292: {"label": False, "conf": "high"},
    293: {"label": False, "conf": "high"},
    294: {"label": False, "conf": "high"},

    # eu_expansion (295-321) ---------------------------------------
    295: {"label": True, "conf": "high"},
    296: {"label": True, "conf": "high"},
    297: {"label": True, "conf": "high"},
    298: {"label": True, "conf": "high"},
    299: {"label": True, "conf": "high"},
    300: {"label": False, "conf": "medium", "note": "EU sanctions Russians = Ukraine support, not accession"},
    301: {"label": True, "conf": "high"},
    302: {"label": True, "conf": "high"},
    303: {"label": True, "conf": "high"},
    304: {"label": False, "conf": "medium", "note": "EU child-deport sanctions, not expansion"},
    305: {"label": False, "conf": "medium", "note": "Putin/EU talks Ukraine — not expansion"},
    306: {"label": False, "conf": "medium", "note": "EU Ukraine mediator — Ukraine war"},
    307: {"label": True, "conf": "high"},
    308: {"label": True, "conf": "high"},
    309: {"label": True, "conf": "high"},
    310: {"label": False, "conf": "medium", "note": "EU sanctions Israeli settlers (EU foreign policy, not expansion)"},
    311: {"label": False, "conf": "high"},
    312: {"label": False, "conf": "medium", "note": "Dup of 310"},
    313: {"label": False, "conf": "high"},
    314: {"label": False, "conf": "medium", "note": "China-EU trade dispute (not expansion)"},
    315: {"label": False, "conf": "medium", "note": "EU defense exercise (not expansion)"},
    316: {"label": False, "conf": "medium", "note": "EU-Mercosur FTA Poland (not expansion)"},
    317: {"label": False, "conf": "high"},
    318: {"label": False, "conf": "medium", "note": "Trump-EU trade deal deadline (not expansion)"},
    319: {"label": False, "conf": "high"},
    320: {"label": False, "conf": "medium", "note": "NATO members expulsion (not EU expansion)"},
    321: {"label": False, "conf": "high"},

    # africa_political_transitions (322-342) -----------------------
    322: {"label": True, "conf": "high"},
    323: {"label": True, "conf": "high", "note": "AU summit Egypt"},
    324: {"label": True, "conf": "high"},
    325: {"label": True, "conf": "high"},
    326: {"label": True, "conf": "high"},
    327: {"label": True, "conf": "high"},
    328: {"label": True, "conf": "high"},
    329: {"label": True, "conf": "high"},
    330: {"label": True, "conf": "high"},
    331: {"label": False, "conf": "high", "note": "Iran military commander Minab; انقلاب hint spurious"},
    332: {"label": True, "conf": "high", "note": "Sudan charity kitchens war"},
    333: {"label": False, "conf": "high", "note": "Tehran prosecutor; انقلاب = Iran Revolution Sq context"},
    334: {"label": False, "conf": "high", "note": "Iran academic community; انقلاب spurious"},
    335: {"label": False, "conf": "high", "note": "Iran illegal construction; انقلاب spurious"},
    336: {"label": False, "conf": "high", "note": "Iran boxing knife attack; مجموعه ورزشی انقلاب = Revolution Sports Complex"},
    337: {"label": False, "conf": "high", "note": "Iran execution Erfan Kiani; انقلاب = Iran's national revolution"},
    338: {"label": True, "conf": "high", "note": "Sudan Khartoum airport"},
    339: {"label": False, "conf": "high", "note": "Iran football coach"},
    340: {"label": False, "conf": "high"},
    341: {"label": False, "conf": "high"},
    342: {"label": False, "conf": "high"},
}
