#!/usr/bin/env python3
"""render_analysis_md.py — render JSON analyses into human-readable markdown.

The canonical analytical artifact is `analyses/<DATE>_<story_key>.json` — the
shape Claude emits, schema-validated against `docs/api/schema/analysis.schema.json`.
This script reads those JSON files and produces matching `.md` files for PR
review and the Pages render.

The MD is a presentation layer. Never the source of truth. If you want to
edit the analysis, edit the JSON.

Usage:
  python render_analysis_md.py                   # all today's analyses
  python render_analysis_md.py --date 2026-05-08 # specific date
  python render_analysis_md.py FILE.json         # specific file
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from meta import REPO_ROOT as ROOT
ANALYSES = ROOT / "analyses"


def render(a: dict) -> str:
    """JSON analysis dict -> markdown string."""
    out: list[str] = []

    # Header
    out.append(f"# {a['story_title']}")
    out.append("")
    out.append(f"**Date:** {a['date']}  ")
    out.append(f"**Story key:** `{a['story_key']}`  ")
    out.append(f"**Coverage:** {a['n_buckets']} buckets, {a['n_articles']} articles  ")
    if a.get("model"):
        out.append(f"**Model:** `{a['model']}`  ")
    out.append(f"**Methodology pin:** `meta_version {a.get('meta_version', '?')}`  ")
    out.append("")
    out.append("---")
    out.append("")

    # TL;DR
    out.append("## TL;DR")
    out.append("")
    out.append(a["tldr"])
    out.append("")

    # Frames
    out.append(f"## Frames ({len(a['frames'])})")
    out.append("")
    for f in a["frames"]:
        out.append(f"### {f['label']}")
        out.append("")
        if f.get("description"):
            out.append(f"_{f['description']}_")
            out.append("")
        out.append(f"**Buckets:** {', '.join(f'`{b}`' for b in f['buckets'])}")
        out.append("")
        for ev in f["evidence"]:
            attribution = f"`{ev['bucket']}`"
            if ev.get("outlet"):
                attribution = f"`{ev['bucket']}` / {ev['outlet']}"
            out.append(f"> {ev['quote'].strip()}")
            out.append(f">")
            out.append(f"> — {attribution} (corpus[{ev['signal_text_idx']}])")
            out.append("")

    # Isolation
    if a.get("isolation_top"):
        out.append("## Most isolated buckets")
        out.append("")
        out.append("| Bucket | mean_jaccard | Note |")
        out.append("| --- | --- | --- |")
        for r in a["isolation_top"]:
            note = r.get("note", "")
            out.append(f"| `{r['bucket']}` | {r['mean_jaccard']} | {note} |")
        out.append("")

    # Exclusive vocab
    if a.get("exclusive_vocab_highlights"):
        out.append("## Bucket-exclusive vocabulary")
        out.append("")
        out.append("| Bucket | Distinctive terms | What it reveals |")
        out.append("| --- | --- | --- |")
        for h in a["exclusive_vocab_highlights"]:
            terms = ", ".join(f"*{t}*" for t in h["terms"])
            reveals = h.get("what_it_reveals", "")
            out.append(f"| `{h['bucket']}` | {terms} | {reveals} |")
        out.append("")

    # Paradox
    out.append("## Paradox")
    out.append("")
    p = a.get("paradox")
    if p is None:
        out.append("_No paradox in this corpus._")
    else:
        out.append(f"**{p['joint_conclusion']}**")
        out.append("")
        for side_key in ("a", "b"):
            s = p[side_key]
            out.append(f"> {s['quote'].strip()}")
            out.append(f">")
            out.append(f"> — `{s['bucket']}` / {s['outlet']} (corpus[{s['signal_text_idx']}])")
            out.append("")
    out.append("")

    # Silences
    if a.get("silences"):
        out.append("## Silence as data")
        out.append("")
        for s in a["silences"]:
            out.append(f"- **`{s['bucket']}`** — {s['what_they_covered_instead']}")
        out.append("")

    # Single-outlet findings
    if a.get("single_outlet_findings"):
        out.append("## Single-outlet findings")
        out.append("")
        for i, f in enumerate(a["single_outlet_findings"], 1):
            ref = (f" (corpus[{f['signal_text_idx']}])"
                   if f.get("signal_text_idx") is not None else "")
            out.append(f"{i}. **{f['outlet']}** (`{f['bucket']}`): {f['finding']}{ref}")
        out.append("")

    # Bottom line
    out.append("## Bottom line")
    out.append("")
    out.append(a["bottom_line"])
    out.append("")

    # Footer
    out.append("---")
    out.append("")
    out.append(
        f"_Generated by `render_analysis_md.py` from "
        f"`analyses/{a['date']}_{a['story_key']}.json`. The JSON is the "
        f"canonical artifact; this markdown is a render._"
    )
    out.append("")

    return "\n".join(out)


def render_one(json_path: Path) -> Path:
    a = json.loads(json_path.read_text(encoding="utf-8"))
    md = render(a)
    md_path = json_path.with_suffix(".md")
    md_path.write_text(md, encoding="utf-8")
    return md_path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("files", nargs="*", type=Path,
                    help="Specific .json analysis files. Default: all for --date.")
    ap.add_argument("--date", default=None,
                    help="Date YYYY-MM-DD. Default: today UTC.")
    args = ap.parse_args()

    if args.files:
        targets = list(args.files)
    else:
        date = args.date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        targets = sorted(ANALYSES.glob(f"{date}_*.json"))
        if not targets:
            print(f"No JSON analyses found for {date}.")
            return 0

    for t in targets:
        if not t.exists():
            print(f"  skip: {t} not found", file=sys.stderr)
            continue
        if t.suffix != ".json":
            print(f"  skip: {t} is not .json", file=sys.stderr)
            continue
        out = render_one(t)
        print(f"  + {t.name:<48} -> {out.name}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
